### ISSUE TITLE
[repo] Inconsistent use of release name for resolving service locations

### ISSUE THREAD

**Issue by eawagner** [devops-ia/helm-opencti#41]
### Describe the bug a clear and concise description of what the bug is.

When using a release name it does not get templated consistently.  For instance to generate the service name for the server it will use the `opencti.fullname` helper function, but the init container on the worker will simply use `$.Release.Name`.  This means that we must use the release name override or simply use the release name of `opencti` when deploying to get consistent behavior.

### What's your helm version?

3.15.4

### What's your kubectl version?

1.30

### Chart version

1.0.0

### What you expected to happen?

Ideally all instances of `$.Release.Name` would get replaced with the `opencti.fullname` helper function when referencing the service.

### How to reproduce it?

simply run `helm install debugging opencti/opencti` and the worker will fail to start because it will try to look for `debugging-server` instead of the service which is named `debugging-opencti-server`.

### Enter the command that you execute when chart failing/misfunctioning

helm install debugging opencti/opencti

**Comment by ialejandro** [comment]
Thx for the report! On our CI use https://github.com/devops-ia/helm-opencti/tree/main/charts/opencti/ci and force use `fullnameOverride` to force the same name on all services and dependencies.

**Comment by eawagner** [comment]
Thank you for the fast turnaround!
