### ISSUE TITLE
worker ready checker config is checking the wrong variable

### ISSUE THREAD

**Issue by eawagner** [devops-ia/helm-opencti#46]
### Describe the bug a clear and concise description of what the bug is.

When disabling the ready checker for the server, it also disables it for the worker because the enabled flag that is being checked isn't for the worker

### What's your helm version?

3.15.4

### What's your kubectl version?

1.30

### Chart version

1.0.0

### Explain bug

When disabling the readyChecker for the external services (as they are being provided externally for me), it also disables the worker readyness checker.

The check on the following line should be changed from `.Values.readyChecker.enabled` to `.Values.worker.readyChecker.enabled`

https://github.com/devops-ia/helm-opencti/blob/main/charts/opencti/templates/worker/deployment.yaml#L41

### What you expected to happen?

When the readyChecker in the worker is enabled but the server readyChecker is disabled the worker should still wait.

### How to reproduce it?

disable readyChecker for the server and enable it for the worker.

### Enter the command that you execute when chart failing/misfunctioning

helm install opencti opencti/opencti -f opencti-values.yaml

**Comment by ialejandro** [comment]
@eawagner sorry, my bad. Failed to replicate from server template. It's already fixed on the new patch version.

Thanks a lot for you reports!

**Comment by eawagner** [comment]
of course, you all have been great!
