### ISSUE TITLE
Example for use with external secret store

### ISSUE THREAD

**Issue by Moorrees1992** [devops-ia/helm-opencti#50]
Hi,

Is it possible to create an example values.yaml file ?

I am getting stuck with setting the right env. variables for the server.
Resulting in incorrect user credentials for rabbitmq...

<img width="881" alt="Scherm­afbeelding 2024-08-30 om 15 42 18" src="https://github.com/user-attachments/assets/6d6ce63c-af7f-46dc-a195-2f73187707a7">

**Comment by ialejandro** [comment]
Hi @Moorrees1992, check the sample: https://github.com/devops-ia/helm-opencti/blob/main/charts/opencti/docs/examples.md#sample. if you still have questions, write re-open the issue.

**Comment by Moorrees1992** [comment]
just to beshure, are the values in the secret segment bogus values? eg. rabbitmq__password: changeme

**Comment by ialejandro** [comment]
yes @Moorrees1992 its only for ci purpose. You should set your secret values, maybe you can use this values (https://github.com/devops-ia/helm-opencti/blob/main/charts/opencti/ci/ci-common-values.yaml) like template for you deployment.
