### ISSUE TITLE
[repo] Offline installation

### ISSUE THREAD

**Issue by AlvaroAguilarAlhama** [devops-ia/helm-opencti#63]
### Is your feature request related to a problem?

When performing an offline installation on Kubernetes using a latest version in the image, by default the imagePullPolicy is set to Always. In the case of this chart, the latest versions of busybox are specified for the server and the worker, so an offline installation is not possible.

### Describe the solution you'd like

The solution may be to indicate a specific version for busybox in the deployment yaml of both applications. Another solution would be to be able to indicate in the values.yaml the version or policy you want for busybox.

### Describe alternatives you've considered

NONE

**Comment by ialejandro** [comment]
Thanks for your comment! When this PR (https://github.com/devops-ia/helm-opencti/pull/64) will merge, the new release 1.6.1 you can configure your tag image for busybox or other base image which you want.
