### ISSUE TITLE
Look for OPENCTI_TOKEN variable from APP__ADMIN__TOKEN if its in envFromSecrets

### ISSUE THREAD

**Issue by eawagner** [devops-ia/helm-opencti#81]
### Is your feature request related to a problem?

Not particularly, but we have our token defined in a secret outside of the chart so we must add the OPENCTI_TOKEN to each worker and connector individually.

### Describe the solution you'd like

To be able to have the chart reuse the configuration defined in the top level envFromSecrets configuration if its defined similar to how it is done if defined in the env or secrets section.

### Describe alternatives you've considered

Simply defining it in each individual connector and for the worker configs

**Comment by ialejandro** [comment]
Hi!

With the next release `1.7.0` (publish soon), maybe can help you with these improves:

On `worker` you can use `worker.envFromSecrets`:

```
worker:
  # -- Variables from secrets
  envFromSecrets: {}
    # MY_VARIABLE:
    #   name: <name-secret>
    #   key: secret_key
```

And on `connector` you can use `connectorsGlobal.envFromSecrets`:

```
connectorsGlobal:
  # -- Variables from secrets
  envFromSecrets: {}
    # MY_VARIABLE:
    #   name: <name-secret>
    #   key: secret_key
```
