### ISSUE TITLE
[repo] version bump

### ISSUE THREAD

**Issue by tob123** [devops-ia/helm-opencti#96]
### Describe the bug a clear and concise description of what the bug is.

Hello, thx a lot for updating the opencti version to 6.3.13 in https://github.com/devops-ia/helm-opencti/pull/94
can you bump the accompanying chart version as well ?
thx a bunch.

### What's your helm version?

.

### What's your kubectl version?

.

### Chart version

1.6.24

### Enter the command that you execute when chart failing/misfunctioning

helm pull https://devops-ia.github.io/helm-opencti --version 1.6.24

**Comment by ialejandro** [comment]
Sorry for the inconvenience! https://github.com/devops-ia/helm-opencti/blob/v1.6.25/charts/opencti/Chart.yaml#L13 on `1.6.25` is already set. FYI, you can set the default `tag` on your `values.yaml` (https://github.com/devops-ia/helm-opencti/blob/v1.6.25/charts/opencti/values.yaml#L22) if you won't wait until new release :)
